#!/bin/bash
# Apex Data API Branding Check Script
# Finds any remaining NASCAR references that need to be updated

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_header() {
  echo -e "${BLUE}🔍 Apex Data API Branding Check${NC}"
  echo "============================================"
  echo ""
}

print_section() {
  local title=$1
  echo ""
  echo -e "${YELLOW}📋 ${title}${NC}"
  echo "----------------------------------------"
}

print_success() {
  echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
  echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
  echo -e "${RED}❌ $1${NC}"
}

# Check for NASCAR references
check_nascar_references() {
  print_section "Checking for NASCAR References"

  local nascar_files=($(grep -r -l -i "nascar" . --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=dist --exclude="*.log" --exclude="branding-check-report*" 2>/dev/null || true))

  if [[ ${#nascar_files[@]} -eq 0 ]]; then
    print_success "No NASCAR references found in codebase"
  else
    print_warning "Found NASCAR references in ${#nascar_files[@]} files:"
    for file in "${nascar_files[@]}"; do
      echo "  - $file"
      # Show the actual lines with NASCAR references
      grep -n -i "nascar" "$file" | head -3 | while read line; do
        echo "    $line"
      done
      echo ""
    done
  fi

  return ${#nascar_files[@]}
}

# Check for lowercase nascar namespace references
check_lowercase_references() {
  print_section "Checking for Lowercase 'nascar' References"

  local nascar_lower_files=($(grep -r -l "nascar" . --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=dist --exclude="*.log" --exclude="branding-check-report*" 2>/dev/null | grep -v -i "NASCAR" | head -10 || true))

  if [[ ${#nascar_lower_files[@]} -eq 0 ]]; then
    print_success "No lowercase 'nascar' namespace references found"
  else
    print_warning "Found lowercase 'nascar' references in ${#nascar_lower_files[@]} files:"
    for file in "${nascar_lower_files[@]}"; do
      echo "  - $file"
      grep -n "nascar" "$file" | head -2 | while read line; do
        echo "    $line"
      done
      echo ""
    done
  fi

  return ${#nascar_lower_files[@]}
}

# Check for apex references (should be present)
check_apex_references() {
  print_section "Checking for Apex References"

  local apex_files=($(grep -r -l -i "apex" . --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=dist --exclude="*.log" --exclude="branding-check-report*" 2>/dev/null | head -5 || true))

  if [[ ${#apex_files[@]} -gt 0 ]]; then
    print_success "Found Apex references in ${#apex_files[@]} files (sample):"
    for file in "${apex_files[@]}"; do
      echo "  ✓ $file"
    done
  else
    print_error "No Apex references found - this might be a problem"
    return 1
  fi

  return 0
}

# Check specific configuration files
check_config_files() {
  print_section "Checking Key Configuration Files"

  local config_files=(
    "package.json"
    "terraform/multi-region.tf"
    "terraform/variables.tf"
    "terraform/outputs.tf"
    "terraform/README.md"
    "src/cache/redis-cache.ts"
    "README.md"
    "VERSIONS.md"
  )

  local issues=0

  for file in "${config_files[@]}"; do
    if [[ -f "$file" ]]; then
      if grep -q -i "nascar" "$file" 2>/dev/null; then
        print_warning "Found NASCAR reference in $file"
        grep -n -i "nascar" "$file" | head -2
        ((issues++))
      else
        print_success "$file is clean"
      fi
    else
      print_warning "$file not found"
    fi
  done

  return $issues
}

# Check Terraform resource names
check_terraform_resources() {
  print_section "Checking Terraform Resource Names"

  if [[ -f "terraform/multi-region.tf" ]]; then
    local nascar_resources=$(grep -n "nascar" terraform/multi-region.tf 2>/dev/null | wc -l || echo "0")

    if [[ "$nascar_resources" -gt 0 ]]; then
      print_warning "Found $nascar_resources NASCAR references in Terraform"
      grep -n "nascar" terraform/multi-region.tf | head -5
      return 1
    else
      print_success "Terraform resources use Apex branding"
      return 0
    fi
  else
    print_warning "terraform/multi-region.tf not found"
    return 1
  fi
}

# Generate branding report
generate_report() {
  print_section "Generating Branding Report"

  local report_file="branding-check-report-$(date +%Y%m%d-%H%M%S).md"

  cat >"$report_file" <<EOF
# Apex Data API Branding Check Report

**Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Generated by:** Branding check script

## Summary

This report shows the current status of branding updates from NASCAR to Apex Data API.

## Files Checked

### Configuration Files
$(for file in package.json terraform/multi-region.tf terraform/variables.tf terraform/outputs.tf terraform/README.md src/cache/redis-cache.ts README.md VERSIONS.md; do
    if [[ -f "$file" ]]; then
      if grep -q -i "nascar" "$file" 2>/dev/null; then
        echo "- ❌ $file (contains NASCAR references)"
      else
        echo "- ✅ $file (clean)"
      fi
    else
      echo "- ⚠️  $file (not found)"
    fi
  done)

### Remaining NASCAR References
$(if grep -r -l -i "nascar" . --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=dist --exclude="*.log" --exclude="branding-check-report*" 2>/dev/null | head -20; then
    echo "Files still containing NASCAR references:"
    grep -r -l -i "nascar" . --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=dist --exclude="*.log" --exclude="branding-check-report*" 2>/dev/null | head -20 | while read file; do
      echo "  - $file"
    done
  else
    echo "✅ No NASCAR references found in codebase"
  fi)

### Apex References Status
$(if grep -r -l -i "apex" . --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=dist --exclude="*.log" --exclude="branding-check-report*" 2>/dev/null | head -5; then
    echo "✅ Apex branding is present in multiple files"
  else
    echo "❌ No Apex references found - this needs investigation"
  fi)

## Recommendations

1. **Critical**: Update any remaining NASCAR references in configuration files
2. **Important**: Update database table comments and schema documentation
3. **Consider**: Update internal comments and documentation
4. **Optional**: Update historical commit messages or logs

## Next Steps

1. Review any files listed above with NASCAR references
2. Update critical configuration and infrastructure files first
3. Consider updating documentation and comments for consistency
4. Test the application after branding updates

---
*This report was generated automatically by the branding check script.*
EOF

  print_success "Branding report generated: $report_file"
  echo "  Review the report for any remaining issues to address."
}

# Main execution
main() {
  print_header

  local total_issues=0

  # Run all checks
  check_nascar_references
  total_issues=$((total_issues + $?))

  check_lowercase_references
  total_issues=$((total_issues + $?))

  check_apex_references
  total_issues=$((total_issues + $?))

  check_config_files
  total_issues=$((total_issues + $?))

  check_terraform_resources
  total_issues=$((total_issues + $?))

  generate_report

  # Summary
  echo ""
  if [[ $total_issues -eq 0 ]]; then
    print_success "🎉 Branding update appears complete!"
    echo "  All checked files use Apex branding consistently."
  else
    print_warning "⚠️  Found $total_issues potential branding issues"
    echo "  Review the generated report for details."
  fi

  echo ""
  echo -e "${BLUE}📋 Next Steps:${NC}"
  echo "  1. Review the generated branding report"
  echo "  2. Update any remaining NASCAR references in critical files"
  echo "  3. Test the application after changes"
  echo "  4. Consider updating documentation and comments"
}

# Run main function
main "$@"
